# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: "en-US"

reviews:
  profile: "assertive"
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  request_changes_workflow: true
  path_instructions:
    - path: "**/*.cs"
      instructions: |
        Review C# code for:
        - Adherence to C# coding conventions and .NET best practices
        - SOLID principles and design patterns
        - Proper use of async/await patterns
        - Exception handling and resource disposal (IDisposable)
        - Null reference handling (nullable reference types)
        - Performance considerations (LINQ efficiency, allocations)
        - Security vulnerabilities (SQL injection, XSS, authentication issues)
        - Thread safety and concurrency issues

    - path: "**/*.csproj"
      instructions: |
        Review project files for:
        - Appropriate package versions and security updates
        - Proper target framework selection
        - Unnecessary or duplicate package references

    - path: "**/Tests/**/*.cs"
      instructions: |
        Review test code for:
        - Test coverage and edge cases
        - Proper use of testing frameworks (xUnit/NUnit/MSTest)
        - Test naming conventions
        - Arrange-Act-Assert pattern
        - Mock usage and test isolation

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
  learnings:
    scope: "auto"
